### ISSUE TITLE
Problem with nonexisting AS-SET

### ISSUE THREAD

**Issue by nelreth** [codeout/irrc#2]
Hi

I've encountered a problem in case when AS-SET has as a member an AS-SET which doesn't exist in RIPE DB.
e.g.
$ irrc -t 4 -h whois.ripe.net -4 AS-MULTIPLAYPOLSKA
E, [2017-01-09T12:21:11.684940 #1447] ERROR -- : '-k -r -a -T as-set AS-MULTIPLAYPOLSKA' failed on 'whois.ripe.net' (101: no entries found).
--- {}

**Comment by codeout** [comment]
I guess that ```AS-MULTIPLAYPOLSKA``` is a customer, you are trying to expand transit AS-SET (which means something like parent) and it fails. Could you tell me what is the parent AS-SET you want to expand so that I can address the problem?

**Comment by nelreth** [comment]
Yes - it's a customer of AS-SET: AS-CDP

Adam

**Comment by codeout** [comment]
Thanks Adam, I could reproduce the problem.
I'm working on this so that next version can appropriately handle whoisd errors.

**Comment by nelreth** [comment]
Great - I'll be waiting for this fix

Adam

**Comment by codeout** [comment]
I'm done fixing it with big performance improvement, but haven't released the gem yet.

Could you try this?

```zsh
$ git clone https://github.com/codeout/irrc.git
$ cd irrc
$ bundle install
$ ruby -I lib exe/irrc -t 4 -h ripe AS-CDP
```

I'll publish version 0.2.0 if your issue is gone.

**Comment by nelreth** [comment]
Excellent - working flawlessly

Thank You

**Comment by codeout** [comment]
0.2.0 has been released :tada: Thanks again for your reporting.
